services:
  moria:
    container_name: moria
    image: ghcr.io/bubylou/moria:latest
    build:
      context: .
      target: image
    ports:
      - 7777:7777/udp
      - 7777:7777/tcp
    volumes:
      - ./moria:/app/moria
      - moria-config:/config/moria
      - moria-data:/data/moria
volumes:
  moria-config:
  moria-data:
